### PR TITLE
Fixed issue with mysessionid

### PR DESCRIPTION
**Pull request by frelars**

### CODE REVIEW

**Comment by idoco** [comment]
Hi, first this is a very cool project and HammerDB looks like a good tool to add to my tool-set!

Regrading session ids, I moved adding messages session ids to the server side to make it harder to impersonate in the chat. When the session id is generated on the client side, a user can set it to be a other user's session id  and send messages on their behalf.

**Comment by frelars** [comment]
Hi idoco, really like your project as well! I'm actually contemplating adding a traditional chat-window ontop mapchat to allow new users to easily see the last conversations and join in. It will also make it possible to look away for a sec or two without missing any replies. Maybe also add a time-line, so it is easy to go back in time and replay discussions..

Re session ids, yes, that is a problem, but one bigger problem for this fork at this time is that the appid is sendt with the HTML, essentially allowing anyone to do whatever they want with the data stored. The solution to this and session ids is to move domain logic to an external domin-object served by HammerDB. The client will then call methods on this object using a local proxy. This will remove sensitive data such as sessionIds and appIds from client reach. Will be added as soon as I have fixed some other pending issues in HammerDB (character encoding..).

**Comment by frelars** [comment]
I'm a bit new to github and forking, but just to make it clear; I have no intention of creating my own rebranded version of MapChat and selling it as my own project. MapChat is your project and I will credit you with a link every time I "use" it. I'm only using MapChat to to test/demonstrate HammerDB features (its a nice simple project with clean code and some good fun!)

**Comment by idoco** [comment]
Thanks @frelars , I appreciate the feedback and the credit :)
I love the idea that MapChat can serve as a small boilerplate to demo other technologies and concepts and happy to support it.

If you feel like implementing new features that can benefit the main branch, I'm really open for that! Please just take into consideration that I still want to keep the code as minimal, clean and elegant as possible, so I might be a little picky about it :)

**Pull request merged**
